#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Author: Tim Henderson
#Email: tim.tadh@hackthology.com
#For licensing see the LICENSE file in the top level directory.

import os
import hmac
from hashlib import sha256

keyfile = os.path.expanduser('~/.ssh/passmash.key')
with open(keyfile) as f:
    key = f.read()

def hash(url, password):
    h = hmac.new(key, password, sha256)
    h.update(url)
    for i in xrange(1000):
        h.update(h.digest())
    return h.digest()

def pretty(hash):
    return hash.encode('hex')[:16]

def main():
    pass    


